---
- hosts: all
  tasks:
    - name: Garantindo dependências
      apt:
        name: 
          - vim
          - curl
          - ca-certificates
          - gnupg
    - name: Garantindo chave do repositório
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Garantindo repositório
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker-ce
        state: present
    - name: Garantindo docker-ce
      apt:
        name: docker-ce
        state: present
    - name: Garantindo docker-compose
      get_url: 
        url: https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "+x"




