#Definição de maquinas do Laboratório do Elastic Stack
machines = {
	"opensearch"       => { "ip" => "10",  "memory" => "4096", "cpus" => "1" },
}

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vbguest.auto_update = false
  machines.each do |name,conf|
    config.vm.define "#{name}" do |srv|
      srv.vm.hostname = "#{name}.example.com"
      srv.vm.network 'private_network', ip: "192.168.63.#{conf["ip"]}"
      srv.vm.provider 'virtualbox' do |vb|
        vb.memory = "#{conf["memory"]}"
        vb.cpus = "#{conf["cpus"]}"
        vb.customize ["modifyvm", :id, "--groups", "/Opensearch"]
      end
      
      srv.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "opensearch.yaml"
        ansible.become = true
      end

    end
  end

end
